spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: frankit_test
    password: 1234
    url: jdbc:mysql://localhost:3306/frankit?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update #create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

jwt:
  secret: ce2a9345d4ed92e2d4be4b8edca68aedffb1b74b018f4c6a6b7a575ec91673ab86e7ffab5d32f4bbc92b19404b723b9e9631937362f90a5bd80d33362d45f3b8
  access-token-expiration-sec: 900     # 15분
  refresh-token-expiration-sec: 1209600 # 14일