spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: frankit_test
    password: 1234
    url: jdbc:mysql://localhost:3306/frankit?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update #create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false